wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.2
batch:
  desc: null
  value: 60
epochs:
  desc: null
  value: 100
loss:
  desc: null
  value: binary-cross-entropy-non-logit
lr:
  desc: null
  value: 0.001
model:
  desc: null
  value: pann-cnn14-attn
optim:
  desc: null
  value: Adam
pred_type:
  desc: null
  value: CLS
resize_dims:
  desc: null
  value: 224x300
seed:
  desc: null
  value: 1024
session:
  desc: null
  value: exp_7_a
