mode: TRA
seed: 1024
classes: 264

train:
  epochs: 100
  batch: 50
  workers: 4
  grad_accum: 2

val:
  freq: 1
  batch: 256
  workers: 4

train_data:
  name: bird_song_v2
  params:
    transformer: DFLT
    audio_transformer: DFLT
    resize: 224x224

val_data:
  name: bird_song_v2_test
  params:
    transformer: DFLT
    audio_transformer: DFLT
    resize: 224x224

model:
  name: resnet50
  params:
    pred_type: CLS
    tune_type: FT
    fc_drop_out_0: 0.2
    fc_drop_out_1: 0.2

optimiser:
  name: AdamW
  params:
    lr: 0.001
    weight_decay: 0.001

scheduler:
  name: CosineAnnealing
  params:
    T_max: 10
    eta_min: 0.00001
  #   mode: max
  #   factor: 0.5
  #   patience: 6
  #   threshold: 0.0005

loss:
  name: cross-entropy

checkpoint:
  type: PRG
  params:
    path: debug_train_1/chkp_wt.pth