mode: TRA
seed: 1024
classes: 2

train:
  epochs: 60
  batch: 20
  workers: 2

val:
  freq: 2
  batch: 20
  workers: 2

train_data:
  name: jh_2020
  params:
    transformer: IMG2
    resize: 224x224

val_data:
  name: jh_2020
  params:
    fold: 3
    transformer: DFLT
    resize: 224x224

model:
  name: resnet152
  params:
    pred_type: CLS
    tune_type: FT
    fc_drop_out: 0.5

optimiser:
  name: AdamW
  params:
    lr: 0.0001
    weight_decay: 0.001

scheduler:
  name: CosineAnnealing-warmup

loss:
  name: cross-entropy