mode: TRA
seed: 1024
classes: 264

train:
  epochs: 100
  batch: 100
  workers: 4
  # grad_accum: 2

val:
  freq: 1
  batch: 300
  workers: 4

train_data:
  name: bird_song
  params:
    transformer: DFLT
    audio_transformer: DFLT
    resize: 128x316 
    fold: 0

val_data:
  name: bird_song
  params:
    transformer: DFLT
    audio_transformer: DFLT
    resize: 128x316
    fold: 0

model:
  name: densenet161
  params:
    pred_type: CLS
    tune_type: FT
    fc_drop_out_0: 0.2
    fc_drop_out_1: 0.2

optimiser:
  name: AdamW
  params:
    lr: 0.001
    weight_decay: 0.001

scheduler:
  name: ReduceLROnPlateau
  params:
    mode: max
    factor: 0.5
    patience: 5
    threshold: 0.0005

loss:
  name: binary-cross-entropy 
