mode: TRA
seed: 1024
classes: 264

train:
  epochs: 60
  batch: 20
  workers: 2
  grad_accum: 2

val:
  freq: 2
  batch: 20
  workers: 2

train_data:
  name: bird_song_v2
  params:
    transformer: DFLT
    audio_transformer: DFLT
    resize: 224x224

val_data:
  name: bird_song_v2
  params:
    transformer: DFLT
    audio_transformer: DFLT
    resize: 224x224

model:
  name: resnext101_32x8d
  params:
    pred_type: CLS
    tune_type: FT
    fc_drop_out: 0.5

optimiser:
  name: AdamW
  params:
    lr: 0.0001
    weight_decay: 0.001

scheduler:
  name: ReduceLROnPlateau
  params:
    mode: max
    factor: 0.5
    patience: 6
    threshold: 0.0005

loss:
  name: cross-entropy