mode: TRA
seed: 1024
classes: 2

train:
  epochs: 3
  batch: 4
  workers: 2

val:
  freq: 1

train_data:
  name: jh_2020
  params:
    fold: 1
    transformer: DFLT
    resize: 224x224

val_data:
  name: jh_2020
  params:
    fold: 1
    transformer: DFLT
    resize: 224x224

model:
  name: densenet161
  params:
    pred_type: CLS
    tune_type: FE
    fc_drop_out: 0.5
    batch_norm_momentum:  0.99

optimiser:
  name: AdamW
  params:
    lr: 0.0001
    weight_decay: 0.001

# scheduler:
#   name: CosineAnnealing
#   params:
#     T_max: 2
#     eta_min: 0.0000001
#     last_epoch: -1

loss:
  name: cross-entropy

checkpoint:
  type: PRG
  params:
    path: new_dummy_1/loss_wt.pth